#!/usr/bin/with-contenv sh
#shellcheck shell=sh

# Copy configuration file to /config if it exists
if [ -f "/opt/plex_dupefinder/config.json" ]
then

    # If an existing config file exists, make a "backup"
    if [ -f "/config/config.json" ]
    then

        if ! diff -q /opt/plex_dupefinder/config.json /config/config.json; then
            cp /config/config.json /config/config.json.previous
        fi
    fi

    # Copy...
    cp /opt/plex_dupefinder/config.json /config/config.json

    # Fix permissions
    chown -R plex_dupefinder:plex_dupefinder /config/*
fi
