#!/usr/bin/with-contenv sh

# Copy configuration if it exists
if [ -f "/config/config.json" ]
then
    cp /config/config.json /opt/plex_dupefinder/config.json
fi

# Create group
groupadd -f -r -g ${PGID} plex_dupefinder

# Create user
useradd -d /config -g ${PGID} -N -r -u ${PUID} plex_dupefinder

# Fix permissions
chown -R plex_dupefinder:plex_dupefinder /opt/plex_dupefinder
