#!/usr/bin/with-contenv sh
#shellcheck shell=sh

# Copy configuration if it exists
if [ -f "/config/config.json" ]
then
    cp /config/config.json /opt/plex_dupefinder/config.json
fi

# Create group
addgroup --gid "${PGID}" plex_dupefinder

# Create user
adduser --system --home /config --ingroup plex_dupefinder --uid "${PUID}" plex_dupefinder

# Fix permissions
chown -R plex_dupefinder:plex_dupefinder /opt/plex_dupefinder
